import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapClient from '@/components/BootstrapClient.js';
import { Providers } from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BIS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Providers>
          {children}
        </Providers>

      <BootstrapClient />
      </body>
    </html>
  );
}
